apiVersion: apps/v1
kind: Deployment
metadata:
  name: packageanddelivery-deployment
  labels:
    app: PackageAndDelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PackageAndDelivery 
  template:
    metadata:
      labels:
        app: PackageAndDelivery
    spec:
      containers:
      - name: projectromscr
        image: projectromscr.azurecr.io/projectromsrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: packageanddeliverysvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApplication22